version: '3'

services:
  minio:
    image: minio/minio
    volumes:
      - miniodata:/data
    env_file:
      - ./envs/minio.env
    ports:
      - 127.0.0.1:9091:9000
    command: server /data

  portainer-agent:
    image: portainer/agent:linux-amd64-1.6.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volume

  portainer:
    image: portainer/portainer:alpine
    restart: always
    command: -H tcp://portainer-agent:9001 --tlsskipverify
    depends_on:
      - portainer-agent
    volumes:
      - portainerdata:/data
    ports:
      - 127.0.0.1:9000:9000

  database:
    image: postgis/postgis:13-3.0-alpine
    container_name: database
    env_file:
      - ./envs/postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432

  app:
    image: ${CI_REGISTRY_IMAGE}:${TAG}
    build:
      context: ./
      dockerfile: Dockerfile
    command: start
    volumes:
      - localedata:/opt/app/locale
    env_file:
      - ./envs/postgres.env
      - ./envs/minio.env
      - ./envs/backend.env
      - ./envs/paybox.env
    depends_on:
      - database
      - minio
    ports:
      - 127.0.0.1:8000:8000

volumes:
  pgdata:
  miniodata:
  portainerdata:
  localedata: