# Generated by Django 2.2 on 2020-10-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Тарифный пакет', 'verbose_name_plural': 'Тарифные пакеты'},
        ),
        migrations.AlterField(
            model_name='package',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Скидка (%)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='month_duration',
            field=models.PositiveSmallIntegerField(verbose_name='Период (в месяцах)'),
        ),
    ]
