# Generated by Django 2.2 on 2020-10-23 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_delete_organizationtariffpackage'),
        ('payment', '0004_auto_20201022_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTariffPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_day', models.PositiveSmallIntegerField(default=15, verbose_name='Кол-во дней')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariffs', to='organizations.Organization')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='payment.Package')),
            ],
            options={
                'verbose_name': 'Тариф организации',
                'verbose_name_plural': 'Тарифы организаций',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('org_tariff_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_payments', to='payment.OrganizationTariffPackage')),
                ('tariff_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_payments', to='payment.Package')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
