# Generated by Django 2.2 on 2020-10-30 07:07

from django.db import migrations, models
import utils.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_organizationtariffpackage_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationtariffpackage',
            name='number_of_day',
        ),
        migrations.AddField(
            model_name='organizationtariffpackage',
            name='duration',
            field=models.DateField(default=utils.datetime.get_default_duration_date, verbose_name='Срок действия до'),
        ),
    ]
