# Generated by Django 2.2 on 2020-10-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20201030_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='month_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена за 1 месяц'),
        ),
    ]
