# Generated by Django 2.2 on 2020-11-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20201030_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата/Время'),
        ),
    ]
