# Generated by Django 2.2 on 2020-11-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_payment_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pg_payment_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID платежа в системе PayBox'),
        ),
    ]
