# Generated by Django 2.2 on 2020-10-03 16:13

import datetime
import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.upload_avatar_file


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('is_department', models.BooleanField(default=False, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Организацию',
                'verbose_name_plural': 'Организаций',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Время начала')),
                ('end_time', models.TimeField(default=datetime.time(18, 0), verbose_name='Время окончания')),
                ('non_fined_minute', models.PositiveSmallIntegerField(default=10, verbose_name='Не штрафуемые минуты')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326,
                                                                            verbose_name='Локация')),
                ('qr_code', models.FileField(blank=True, null=True, upload_to=utils.upload_avatar_file.upload_instance,
                                             verbose_name='QR-код')),
                ('radius', models.PositiveSmallIntegerField(default=100, verbose_name='Радиус')),
            ],
            options={
                'verbose_name': 'Настройка организации',
                'verbose_name_plural': 'Настройки организаций',
            },
        ),
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Отмечен')),
                ('start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Время начала')),
                ('end_time', models.TimeField(default=datetime.time(18, 0), verbose_name='Время окончания')),
                ('non_fined_minute', models.PositiveSmallIntegerField(default=10, verbose_name='Не штрафуемые минуты')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   to='organizations.Organization')),
            ],
            options={
                'verbose_name': 'Организация пользователя',
                'verbose_name_plural': 'Организаций пользователей',
            },
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время входа')),
                ('end_time', models.DateTimeField(null=True, verbose_name='Время выхода')),
                ('is_late', models.BooleanField(default=False, verbose_name='Опоздал')),
                ('user_organization',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_times',
                                   to='organizations.UserOrganization')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
            },
        ),
    ]
