# Generated by Django 2.2 on 2020-10-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationtariffpackage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationTariffPackage',
        ),
    ]
